apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-service
  template:
    metadata:
      labels:
        app: webapp-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8030"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: webapp-service-container
          image: pradeepdhavakumar/webapp-service-image:1.8
          ports:
            - containerPort: 8030  # Change this if your app uses a different port
