apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp-service
  ports:
    - port: 80               # Port to expose within the cluster
      targetPort: 8030       # Port your container listens on
      nodePort: 30080        # External access port (adjust as needed, range: 30000–32767)
