apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service-container
          image: pradeepdhavakumar/searchserviceimage:1.1
          ports:
            - containerPort: 8031  # Change this if your app uses a different port
